name = "week-13-offline"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqd3RfaWQiOjEsInNlY3VyZV9rZXkiOiJza19SVS00RnRWWTFQUjgtRlg3U1FGOEQiLCJhcGlfa2V5IjoiMDFLMDNEOUJHWFE5N1JaQTlKVzQxREVIUTMiLCJ0ZW5hbnRfaWQiOiI2M2EzZjUxMjYwZTQ5MWVkMzU5N2MyMDEzOGY5MWI4NGE2M2MxNWU5ZjdmYzFhNDg0ZWZmNTNiODA4ZWVjMzRhIiwiaW50ZXJuYWxfc2VjcmV0IjoiMGRlNTg5N2QtYzhlNi00ZDNlLTlmMzEtNTdmN2U0YmMyNjg1In0.YxcuLGEb6ULYXwIluq2K8svki68VThqptO20xKHbT_4"
GROQ_API_KEY="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"
ACCESS_TOKEN_SECRET = "NKJNEKJFNEFJ"
REFRESH_TOKEN_SECRET="FNEKJNEhjeFE"
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""
compatibility_flags = ["nodejs_compat"]
[build]
upload.exclude = [
  "**/*.test.ts",
  "**/__tests__/**",
  "**/__mock__/**",         # ← this is what you need!
  "**/__mocks__/**",
  "**/test-utils/**",
  "vitest.config.ts",
  "vite.config.ts"
]
