name = "week-13-offline"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL = ""
JWT_SECRET = ""
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""
compatibility_flags = ["nodejs_compat"] 

[[queues.producers]]
queue ="user_events"
binding="USER_EVENTS_QUEUE"

[[queues.consumers]]
queue="users_events"
binding="USER_EVENTS_QUEUE"