name = "week-13-offline"
main = "src/index.ts"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqd3RfaWQiOjEsInNlY3VyZV9rZXkiOiJza19SVS00RnRWWTFQUjgtRlg3U1FGOEQiLCJhcGlfa2V5IjoiMDFLMDNEOUJHWFE5N1JaQTlKVzQxREVIUTMiLCJ0ZW5hbnRfaWQiOiI2M2EzZjUxMjYwZTQ5MWVkMzU5N2MyMDEzOGY5MWI4NGE2M2MxNWU5ZjdmYzFhNDg0ZWZmNTNiODA4ZWVjMzRhIiwiaW50ZXJuYWxfc2VjcmV0IjoiMGRlNTg5N2QtYzhlNi00ZDNlLTlmMzEtNTdmN2U0YmMyNjg1In0.YxcuLGEb6ULYXwIluq2K8svki68VThqptO20xKHbT_4"
GROQ_API_KEY="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"
ACCESS_TOKEN_SECRET = "NKJNEKJFNEFJ"
REFRESH_TOKEN_SECRET="FNEKJNEhjeFE"

compatibility_flags = ["nodejs_compat"]

triggers = { crons = ["* * * * *"] }

## kv_namespaces
[[kv_namespaces]]
binding = "Blog_cache"
id = "7b7a2eb1fcaa43d19881d8dec6c97ab7"

[[durable_objects.bindings]]
name = "Blog_queue"
class_name = "BlogUpdateQueue"

[[durable_objects.bindings]]
name = "Blog_DD"
class_name = "BlogDD"


# If you also want persistence:
[[migrations]]
tag = "v1"
new_classes = ["BlogUpdateQueue","BlogDD"]
